kind: pipeline
type: docker
name: curs/vue-elements:staging

steps:
  - name: build-and-push-to-registry
    image: plugins/docker
    commands:
    settings:
      debug: true
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      repo: hub.docker.axeta.ru/curs/vue-elements
      registry: hub.docker.axeta.ru
      tags: staging
  - name: trigger-deployment
    image: plugins/webhook
    commands:
    settings:
      urls: http://webhook.axetacloud.ru/hooks/curs.vue-elements.staging
      username:
        from_secret: cloud_webhook_username
      password:
        from_secret: cloud_webhook_password

trigger:
  branch:
    - drone-ci
